development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # url: redis://redis:6379/0

test:
  adapter: test

production:
  adapter: redis
  url: redis://redis:6379/0
  channel_prefix: blog_production

  # <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
