default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: localhost
  url: <%= ENV['DATABASE_URL'] %>
  sslmode: disable

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  sslmode: disable

production:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  url: <%= ENV['DATABASE_URL'] %>
  sslmode: disable
